"""Add agent_memory model

Revision ID: 6065a35b6e6f
Revises: 76233e0818a6
Create Date: 2026-07-21 11:26:37.219757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6065a35b6e6f'
down_revision: Union[str, Sequence[str], None] = '76233e0818a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_memory_thread', 'agent_memory', ['thread_id'], unique=False)
    op.create_index(op.f('ix_agent_memory_thread_id'), 'agent_memory', ['thread_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_memory_thread_id'), table_name='agent_memory')
    op.drop_index('idx_agent_memory_thread', table_name='agent_memory')
    op.drop_table('agent_memory')
    # ### end Alembic commands ###
